name: Tag

on:
  push:
    tags:
      - v*

jobs:
  tag:
    name: Tag Submodules
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tag module cm
        run: |
            git tag cm/${{ github.ref_name }} ${{ github.ref_name }}
            git push origin cm/${{ github.ref_name }}

      - name: Tag module qux
        run: |
            git tag qux/${{ github.ref_name }} ${{ github.ref_name }}
            git push origin qux/${{ github.ref_name }}
