name: Tag

on:
  push:
    tags:
      - v*

jobs:
  tag:
    name: Tag Submodules
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create submodule tags
        run: |
          find */**/go.mod | xargs dirname | xargs -n1 -I % git tag %/${{ github.ref_name }} ${{ github.ref_name }}
          find */**/go.mod | xargs dirname | xargs -n1 -I % git push origin %/${{ github.ref_name }}
